Promise
===

```
//Promise 선언
var _promise = function (param) {
	return new Promise(function (resolve, reject) {

		// 비동기를 표현하기 위해 setTimeout 함수를 사용 
		window.setTimeout(function () {

			// 파라메터가 참이면, 
			if (param) {

				// 해결됨 
				resolve("해결 완료");
			}

			// 파라메터가 거짓이면, 
			else {

				// 실패 
				reject(Error("실패!!"));
			}
		}, 3000);
	});
};

//Promise 실행
_promise(true)
.then(function (text) {
	// 성공시
	console.log(text);
}, function (error) {
	// 실패시 
	console.error(error);
});
```
실행 결과는 콘솔로그로 "해결 완료"

__Promise 선언__ 과 __실행__ 두 부분으로 나눌 수 있다.

### Promise 선언
Promise는 말 그대로 '약속'이다. 따라서 promise는 다음 중 하나의 상태가 될 것이다.

- pending
	- 아직 약속을 수행 중인 상태 (filfilled or reject)
	- new Promise로 Promise가 생성되는 직후부터 resolve or reject가 호출되기 전까지 순간이 pending 상태
- fulfilled
	- promise가 지켜진 상태
- rejected
	- promise가 못 지켜진 상태
- settled
	- promise가 지켜지든 안지켜졌든 결론이 난 상태

### Promise 실행
_promise()를 호출하면 Promise 객체가 리턴된다. 

Promise 객체에는 정상적으로 비동기 작업이 완료되었을 때 호출하는 then이라는 API가 존재한다.

then API는 성공시 호출할 함수를 첫번째 파라메터에, 실패시 호출할 함수를 두번째 파라메터에 선언하면 Promise 상태에 따라 수행하게 된다.

### Promise.catch API
체이닝형태로 연결된 상태에서 비동기 작업이 중간에 에러가날때 사용하는 API.

```.then(null, function(){})```

```
_promise(true)
	.then(JSON.parse)
	.catch(function () { 
		window.alert('체이닝 중간에 에러가!!');
	})
	.then(function (text) {
		console.log(text);
	});
```
```
asyncThing1()
	.then(function() { 
		return asyncThing2();
	})
	.then(function() { 
		return asyncThing3();
	})
	.catch(function(err) { 
		return asyncRecovery1();
	})
	.then(function() { 
		return asyncThing4();
	}, function(err) { 
		return asyncRecovery2(); 
	})
	.catch(function(err) { 
		console.log("Don't worry about it");
	})
	.then(function() { 
		console.log("All done!");
	});
```

### Promise.all API
여러개 비동기 작업들이 존재하고 이들이 모두 완료되었을 때 작업을 진행하고 싶다면 Promise.all API를 활용.

```
var promise1 = new Promise(function (resolve, reject) {

	// 비동기를 표현하기 위해 setTimeout 함수를 사용 
	window.setTimeout(function () {

		// 해결됨 
		console.log("첫번째 Promise 완료");
		resolve("11111");

	}, Math.random() * 20000 + 1000);
});

var promise2 = new Promise(function (resolve, reject) {

	// 비동기를 표현하기 위해 setTimeout 함수를 사용 
	window.setTimeout(function () {

		// 해결됨 
		console.log("두번째 Promise 완료");
		resolve("222222");

	}, Math.random() * 10000 + 1000);
});


Promise.all([promise1, promise2]).then(function (values) {
	console.log("모두 완료됨", values);
});
```
return하지 않고 바로 new Promise로 생성한 경우 Promise 객체에 파라메터로 넘겨준 익명함수는 즉각 실행된다.

즉각 실행되므로 _promise.then(alert)등의 형태로 사용할 수 있다.

함수를 실행해서 새로운 Promise를 리턴하는 형태는 항상 Promise 안의 로직이 함수 실행시 마다 새로 실행된다. 이 함수를 실행해서 리턴된 프로미스 인스턴스는 프로미스 내부의 실행 로직을 결과에 따라 매번 성공하거나 실패할 수 있다.

반면 바로 Promise 인스턴스를 만들어서 실행하게되면 promise 인스턴스는 결과가 다시 바뀔일이 없다. 프로미스 내의 로직이 다시 실행되지 않는다. 한번 결과가 결정되면 바뀌지 않는 특징이 있다.

```
var promise1 = function () {

	return new Promise(function (resolve, reject) {

		// 비동기를 표현하기 위해 setTimeout 함수를 사용 
		window.setTimeout(function () {

			// 해결됨 
			console.log("첫번째 Promise 완료");
			resolve("11111");

		}, Math.random() * 20000 + 1000);
	});
};

var promise2 = function () {

	return new Promise(function (resolve, reject) {

		// 비동기를 표현하기 위해 setTimeout 함수를 사용 
		window.setTimeout(function () {

			// 해결됨 
			console.log("두번째 Promise 완료");
			resolve("2222");

		}, Math.random() * 10000 + 1000);
	});
};

Promise.all([promise1(), promise2()]).then(function (values) {
	console.log("모두 완료됨", values);
});
```

---

JavaScript Promises: an Introduction
===
> https://developers.google.com/web/fundamentals/getting-started/primers/promises?hl=ko#whats-all-the-fuss-about

JavaScript is single threaded, meaning that two bits of script cannot run at the same time; they have to run one after another.

```
var img1 = document.querySelector('.img-1');

img1.addEventListener('load', function() {
  // woo yey image loaded
});

img1.addEventListener('error', function() {
  // argh everything's broken
});
```

At their most basic, promises are a bit like event listeners except:
- A promise can only succeed or fail once. It cannot succeed or fail twice, either can it switch from success to failure or vice versa.
- If a promise has succeeded or failed and you later add a success/failure callback, the correct callback will be called, even though the event took place earlier. 

This is extremely useful for async success/failure, because you're less interested in the exact time something became available, and more interested in reaction to the outcom.

### Promise terminology

- fulfilled	- The action relating to the promise succeeded.
- rejected	- The action relating to the promise failed.
- pending	- Hasn't fulfilled or rejected yet.
- settled	- Has fulfilled or rejected.

How you create a promise

```
var promise = new Promise(function (resolve, reject) { 
// promise 생성자는 resolve, reject등 두 매개변수를 가진 콜백인 단일 인수를 취한다.
  // do a thing, possibly async, then…

  if (/* everything turned out fine */) {
    resolve("Stuff worked!");
  }
  else {
    reject(Error("It broke"));
  }
});
```
How you use that promise

```
promise.then(function(result) { 
// 성공 사례에 대한 콜백과 실패 사례에 대한 콜백 둥 두 인수를 취한다. 둘 다 선택 사항이다.
  console.log(result); // "Stuff worked!"
}, function(err) {
  console.log(err); // Error: "It broke"
});
```

### Promisifying XMLHttpRequest

```
function get(url) {
  // Return a new promise.
  return new Promise(function(resolve, reject) {
    // Do the usual XHR stuff
    var req = new XMLHttpRequest();
    req.open('GET', url);

    req.onload = function() {
      // This is called even on 404 etc
      // so check the status
      if (req.status == 200) {
        // Resolve the promise with the response text
        resolve(req.response);
      }
      else {
        // Otherwise reject with the status text
        // which will hopefully be a meaningful error
        reject(Error(req.statusText));
      }
    };

    // Handle network errors
    req.onerror = function() {
      reject(Error("Network Error"));
    };

    // Make the request
    req.send();
  });
}

```

```
 get('story.json').then(function(response) {
  console.log("Success!", response);
}, function(error) {
  console.error("Failed!", error);
})
```

### Chaining

then() isn't the end of the story, you can chain __then__s together to transform values or run additional async actions one after another.

#### Transforming values

```
var promise = new Promise(function(resolve, reject){
	resolve(1);
});

promise.then(function(val){
	console.log(val);	// 1
	return val + 2;
}).then(function(val){
	console.log(val);	// 3
})
```

```
get('story.json').then(function(response){
	return JSON.parse(response);
}).then(function(response){
	console.log('JSON!', response);
})
```
```
get('story.json').then(JSON.parse).then(function(response){
	console.log('JSON!', response);
})
```
```
function getJson(url){
	return get(url).then(JSON.parse);
}
```
#### Queuing asynchronous actions 
비동기 작업을 큐에 저장

You can also chain 'then's to run async actions in sequence. 비동기 작업을 순서대로 실행할 수 있다.
```
var storyPromise;

function getChart(i) {
	storyPromise = storyPromise || getJSON('story.json');
	// OR 연산자. true or false return

	return storyPromise.then(function(story){
		return getJSON(story.chapterUrls[i]);
	})
}

getChapter(0).then(function(chapter){
	console.log(chapter);
	return getChapter(1);
}).then(function(chapter){
	console.log(chapter);
})
```

### Error handing
오류 처리

```
get('story.json').then(function(response){
	console.log("Success!", response);
}, function(error){
	console.log('Failed!', error);
})
```
```
get('story.json').then(function(response){
	console.log('Success!', response);
}).catch(function(error){
	console.log('Failed!',error);
})
```
```
get('story.json').then(function(response){
	console.log('Success!',response);
}).then(undefined, function(error){
	console.log('Failed', error);
})
```
```
asyncThing1()
	.then(function() { return asyncThing2(); })
	.then(function() { return asyncThing3(); })
	.catch(function(err) { return asyncRecovery1(); })
	.then(function() { return asyncthing4(); }, function(err) { return asyncRecovery2(); })
	.catch(function(err) { console.log("error")})
	.then(function() { console.log('all done'); })
```